name: afcm_egypt

description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  get_storage: ^2.1.1
  shared_preferences: ^2.2.1
  image: ^4.0.17
  flutter_image_filters: ^0.0.16
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  camera: ^0.10.5+3
  tflite: ^1.1.2
  get: ^4.6.4
  flutter_spinkit: ^5.2.0
  hexcolor: ^3.0.1
  animated_widgets: ^1.1.0


  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:

    - assets/image/
    - assets/

  fonts:
    - family: jannah
      fonts:
        - asset: assets/fonts/jannah.ttf

    - family: fireCode
      fonts:
        - asset: assets/fonts/fire_code.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf